//! End-to-end loop through the binary: init, next, edit, done, skip, status, report.

use std::fs;
use std::path::PathBuf;

use assert_cmd::Command;
use predicates::prelude::*;
use serde_json::Value;
use tempfile::TempDir;

const CONFIG: &str = r#"
prompt: |
  PROMPT PLACEHOLDER
rules:
  comment:
    - plain english
    - says why
  identifier:
    - plain english
    - no filler
    - fits convention
  string:
    - plain english
chunk_size: 50
strings:
  min_words: 2
"#;

const LIB: &str = r#"/// Utilizes the robust helper to seamlessly parse the input.
pub fn process_validated_user_data_result(validated_input: &str) -> String {
    // Leverage the helper to compute the final result
    let processed_result = validated_input.trim();
    let message = "An unexpected error has occurred while processing";
    processed_result.to_string() + message
}
"#;

const LIB_EDITED: &str = r#"/// Utilizes the robust helper to seamlessly parse the input.
pub fn process_validated_user_data_result(validated_input: &str) -> String {
    let result = validated_input.trim();
    let message = "An unexpected error has occurred while processing";
    result.to_string() + message
}
"#;

const GEN: &str = r#"// Code generated by tool. DO NOT EDIT.
pub fn generated_helper_function_one(generated_argument: i32) -> i32 { generated_argument }
"#;

const OTHER: &str = r#"pub struct SomeOtherType {
    pub some_field_name: u32,
}
"#;

struct Project {
    dir: TempDir,
    config: PathBuf,
}

fn setup() -> Project {
    let dir = tempfile::tempdir().unwrap();
    fs::create_dir_all(dir.path().join("src")).unwrap();
    fs::write(dir.path().join("src/lib.rs"), LIB).unwrap();
    fs::write(dir.path().join("src/gen.rs"), GEN).unwrap();
    fs::write(dir.path().join("src/other.rs"), OTHER).unwrap();
    let config = dir.path().join("config.yaml");
    fs::write(&config, CONFIG).unwrap();
    Project { dir, config }
}

fn unclop(p: &Project) -> Command {
    let mut c = Command::cargo_bin("unclop").unwrap();
    c.current_dir(p.dir.path()).env("UNCLOP_CONFIG", &p.config);
    c
}

fn json(p: &Project, args: &[&str]) -> Value {
    let out = unclop(p).args(args).output().unwrap();
    serde_json::from_slice(&out.stdout).unwrap_or_else(|e| {
        panic!(
            "not json: {e}\n{}\n{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        )
    })
}

fn items(next: &Value) -> Vec<Value> {
    next["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter().cloned())
        .collect()
}

fn id_where(items: &[Value], f: impl Fn(&Value) -> bool) -> String {
    items
        .iter()
        .find(|i| f(i))
        .unwrap_or_else(|| panic!("no item matched in {items:#?}"))["id"]
        .as_str()
        .unwrap()
        .to_string()
}

#[test]
fn full_loop() {
    let p = setup();

    unclop(&p)
        .arg("init")
        .assert()
        .success()
        .stdout(predicate::str::contains("Scanned 3 files"))
        .stdout(predicate::str::contains("then: unclop next"));

    unclop(&p)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains("PROMPT PLACEHOLDER"))
        .stdout(predicate::str::contains("Rules for identifiers:"))
        .stdout(predicate::str::contains("## src/gen.rs"))
        .stdout(predicate::str::contains("## src/lib.rs"))
        .stdout(predicate::str::contains("unclop done "))
        .stdout(predicate::str::contains(
            "process_validated_user_data_result",
        ));

    // The first chunk holds everything, so re-asking without progress is refused.
    unclop(&p)
        .arg("next")
        .assert()
        .code(2)
        .stdout(predicate::str::contains("Unfinished from your last chunk"));

    let chunk = json(&p, &["next", "--force", "--__JSON__"]);
    assert_eq!(chunk["exit_code"], 0);
    let all = items(&chunk);
    let in_lib = |i: &Value| i["path"] == "src/lib.rs";
    let doc_id = id_where(&all, |i| in_lib(i) && i["kind"] == "doc");
    let comment_id = id_where(&all, |i| in_lib(i) && i["kind"] == "comment");
    let var_id = id_where(&all, |i| i["text"] == "processed_result");
    let string_id = id_where(&all, |i| in_lib(i) && i["kind"] == "string");
    let param_id = id_where(&all, |i| i["text"] == "validated_input");
    assert_eq!(
        all.iter().find(|i| i["id"] == var_id.as_str()).unwrap()["rules"],
        "1,2,3"
    );

    // Rename the variable, delete the comment, leave the doc alone.
    fs::write(p.dir.path().join("src/lib.rs"), LIB_EDITED).unwrap();

    unclop(&p)
        .args([
            "done",
            &format!("{var_id}:1,2,3"),
            &format!("{comment_id}:1,2"),
            &format!("{doc_id}:1,2"),
        ])
        .assert()
        .code(1)
        .stdout(predicate::str::contains(": done"))
        .stdout(predicate::str::contains(
            "gone from source, counted as done",
        ))
        .stdout(predicate::str::contains("unchanged since it was issued"));

    unclop(&p)
        .args(["done", &format!("{doc_id}:1,2"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(format!("{doc_id}: done")));

    // Partial ticks leave the item pending and say what is left.
    unclop(&p)
        .args(["done", &format!("{string_id}:1"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(": done"));
    unclop(&p)
        .args(["done", &format!("{param_id}:1,3"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains("rules 2 still unchecked"));

    unclop(&p)
        .args(["skip", "--file", "src/gen.rs"])
        .assert()
        .success()
        .stdout(predicate::str::contains("src/gen.rs: file skipped"));

    unclop(&p)
        .arg("status")
        .assert()
        .code(1)
        .stdout(predicate::str::contains("src/gen.rs"))
        .stdout(predicate::str::contains("pending"));

    // Skip whatever is left, then everything is settled.
    let status = json(&p, &["status", "--__JSON__"]);
    assert!(status["pending"].as_u64().unwrap() > 0);
    let remaining = json(&p, &["next", "--force", "--__JSON__"]);
    let left: Vec<String> = items(&remaining)
        .iter()
        .map(|i| i["id"].as_str().unwrap().to_string())
        .collect();
    assert!(!left.is_empty());
    let mut skip = unclop(&p);
    skip.arg("skip");
    for id in &left {
        skip.arg(id);
    }
    skip.assert().success();

    unclop(&p).arg("status").assert().success();

    unclop(&p)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "Nothing pending. Run: unclop report",
        ));

    unclop(&p)
        .arg("report")
        .assert()
        .success()
        .stdout(predicate::str::contains("was: processed_result"))
        .stdout(predicate::str::contains("kept: Utilizes the robust helper"))
        .stdout(predicate::str::contains("skipped:"))
        .stdout(predicate::str::contains("Skipped files:"))
        .stdout(predicate::str::contains("src/gen.rs"));

    // The renamed variable is resolvable by the id it was issued under.
    let report = json(&p, &["report", "--__JSON__"]);
    let renamed = report["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter())
        .find(|i| i["was"] == "processed_result")
        .expect("renamed item in report");
    assert_eq!(renamed["text"], "result");
    assert_eq!(renamed["status"], "done");
}

#[test]
fn workers_split_files() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    let a = json(&p, &["next", "--worker", "1/2", "--__JSON__"]);
    let b = json(&p, &["next", "--worker", "2/2", "--__JSON__"]);
    let files = |v: &Value| -> Vec<String> {
        v["files"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f["path"].as_str().unwrap().to_string())
            .collect()
    };
    for (w, v) in [("1/2", &a), ("2/2", &b)] {
        if files(v).is_empty() {
            assert_eq!(v["then"], "unclop report");
        } else {
            assert_eq!(v["then"], format!("unclop next --worker {w}"));
        }
    }
    let (fa, fb) = (files(&a), files(&b));
    assert!(
        fa.iter().all(|f| !fb.contains(f)),
        "workers overlap: {fa:?} {fb:?}"
    );
    let mut all = fa.clone();
    all.extend(fb);
    all.sort();
    assert_eq!(all, vec!["src/gen.rs", "src/lib.rs", "src/other.rs"]);
}

#[test]
fn reopen_changed_after_done() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    let chunk = json(&p, &["next", "--__JSON__"]);
    let all = items(&chunk);
    let var_id = id_where(&all, |i| i["text"] == "processed_result");
    unclop(&p)
        .args(["done", &format!("{var_id}:1,2,3"), "--keep"])
        .assert()
        .success();

    // A later edit to a done item keeps it done but flags it.
    fs::write(p.dir.path().join("src/lib.rs"), LIB_EDITED).unwrap();
    let report = json(&p, &["report", "--__JSON__"]);
    let item = report["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter())
        .find(|i| i["text"] == "result")
        .expect("renamed item");
    assert_eq!(item["status"], "done");

    unclop(&p)
        .args(["reopen", "--changed"])
        .assert()
        .success()
        .stdout(predicate::str::contains("1 items that changed"));
    let status = json(&p, &["status", "--__JSON__"]);
    assert_eq!(status["totals"]["done"], 0);
}

#[test]
fn only_takes_one_category() {
    let p = setup();
    unclop(&p).arg("init").assert().success();

    unclop(&p)
        .args(["next", "--only", "identifier"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Rules for identifiers:"))
        .stdout(predicate::str::contains("Rules for comments:").not())
        .stdout(predicate::str::contains("pending identifiers in this file"));

    let chunk = json(
        &p,
        &["next", "--only", "identifiers", "--force", "--__JSON__"],
    );
    assert_eq!(chunk["only"], "identifier");
    let idents = items(&chunk);
    assert!(!idents.is_empty());
    assert!(idents.iter().all(|i| i["category"] == "identifiers"));

    let mut skip = unclop(&p);
    skip.arg("skip");
    for i in &idents {
        skip.arg(i["id"].as_str().unwrap());
    }
    skip.assert().success();

    unclop(&p)
        .args(["next", "--only", "identifier"])
        .assert()
        .success()
        .stdout(predicate::str::contains("No identifiers pending."))
        .stdout(predicate::str::contains("remain in other categories"));

    let chunk = json(&p, &["next", "--only", "comment", "--__JSON__"]);
    let comments = items(&chunk);
    assert!(!comments.is_empty());
    assert!(comments.iter().all(|i| i["category"] == "comments"));

    unclop(&p)
        .args(["next", "--only", "names"])
        .assert()
        .code(2)
        .stderr(predicate::str::contains("identifier, comment or string"));
}

#[test]
fn then_line_keeps_the_flags() {
    let p = setup();
    unclop(&p).arg("init").assert().success();

    let chunk = json(&p, &["next", "--only", "identifier", "--__JSON__"]);
    assert_eq!(chunk["then"], "unclop next --only identifier");
    let idents = items(&chunk);
    let (first, rest) = idents.split_first().unwrap();
    assert!(!rest.is_empty());

    // done is the last thing the agent reads, so it has to repeat the filter.
    unclop(&p)
        .args([
            "done",
            &format!("{}:1,2,3", first["id"].as_str().unwrap()),
            "--keep",
        ])
        .assert()
        .success()
        .stdout(predicate::str::ends_with(
            "then: unclop next --only identifier\n",
        ));

    // Settling the last identifier drops the filter.
    let mut skip = unclop(&p);
    skip.arg("skip");
    for i in rest {
        skip.arg(i["id"].as_str().unwrap());
    }
    skip.assert()
        .success()
        .stdout(predicate::str::ends_with("then: unclop next\n"));
}

#[test]
fn agent_sees_the_rules_and_no_way_around_them() {
    let p = setup();
    unclop(&p).arg("init").assert().success();

    unclop(&p)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "PROMPT PLACEHOLDER\n\nRules for using unclop.",
        ))
        .stdout(predicate::str::contains("Never write or run a script"))
        .stdout(predicate::str::contains(
            "Do not create or edit .unclop.yaml in the project root",
        ));

    unclop(&p)
        .arg("next")
        .assert()
        .code(2)
        .stdout(predicate::str::contains("Unfinished from your last chunk"))
        .stdout(predicate::str::contains("--force").not());

    // clap suggests similar flags, hidden ones included, so --json must not lead to --__JSON__.
    unclop(&p)
        .args(["next", "--json"])
        .assert()
        .code(2)
        .stderr(predicate::str::contains("unexpected argument '--json'"))
        .stderr(predicate::str::contains("JSON__").not());

    for hidden in ["--force", "JSON__", "--config"] {
        unclop(&p)
            .args(["next", "--help"])
            .assert()
            .success()
            .stdout(predicate::str::contains(hidden).not());
    }
}

const CONFIG_MD: &str = r#"---
chunk_size: 50
---

PROMPT PLACEHOLDER

## Identifiers

1. Plain english: no filler, no "slop".
2. no filler
3. fits convention

## Comments

Comments only: say why, not what.

1. plain english
2. says why

## Strings

1. plain english
"#;

#[test]
fn markdown_config() {
    let p = setup();
    let md = p.dir.path().join("config.md");
    fs::write(&md, CONFIG_MD).unwrap();
    let with_md = |args: &[&str]| {
        let mut c = unclop(&p);
        c.env("UNCLOP_CONFIG", &md).args(args);
        c
    };
    with_md(&["init"]).assert().success();

    with_md(&["next", "--only", "identifier"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "  1. Plain english: no filler, no \"slop\".\n",
        ))
        .stdout(predicate::str::contains("Comments only").not());
    with_md(&["next", "--only", "comment", "--force"])
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "Comments only: say why, not what.\n\nRules for comments:\n  1. plain english\n",
        ));

    fs::write(&md, CONFIG_MD.replace("## Strings", "## Prose")).unwrap();
    with_md(&["next", "--force"])
        .assert()
        .code(70)
        .stderr(predicate::str::contains(
            "config.md: line 20: unknown section \"## Prose\"",
        ));
}

#[test]
fn init_writes_a_markdown_config() {
    let p = setup();
    let md = p.dir.path().join("fresh/config.md");
    unclop(&p)
        .env("UNCLOP_CONFIG", &md)
        .arg("init")
        .assert()
        .success()
        .stdout(predicate::str::contains("Wrote config"));
    assert!(fs::read_to_string(&md).unwrap().contains("## Identifiers"));
    unclop(&p)
        .env("UNCLOP_CONFIG", &md)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains("1. IDENTIFIER RULE PLACEHOLDER 1"));
}

const TWINS: &str = "fn one() { let running_total = 1; }
fn two() { let running_total = 2; }
";

const TWINS_EDITED: &str = "fn one() { let total = 1; }
fn two() { let running_total = 2; }
";

#[test]
fn renaming_one_of_two_same_names() {
    let p = setup();
    let twins = p.dir.path().join("src/twins.rs");
    fs::write(&twins, TWINS).unwrap();
    unclop(&p).arg("init").assert().success();
    let chunk = json(&p, &["next", "--__JSON__"]);
    let ids: Vec<String> = items(&chunk)
        .iter()
        .filter(|i| i["path"] == "src/twins.rs" && i["kind"] == "var")
        .map(|i| i["id"].as_str().unwrap().to_string())
        .collect();
    assert_eq!(ids.len(), 2);
    assert_eq!(ids[1], format!("{}~2", ids[0]));

    fs::write(&twins, TWINS_EDITED).unwrap();

    // The unfinished list shows each item under the id the chunk printed for it.
    unclop(&p)
        .arg("next")
        .assert()
        .code(2)
        .stdout(predicate::str::contains(format!(
            "  {:<13} var      L1        total  in fn one",
            ids[0]
        )))
        .stdout(predicate::str::contains(format!(
            "  {:<13} var      L2        running_total  in fn two",
            ids[1]
        )));

    unclop(&p)
        .args(["done", &format!("{}:1,2,3", ids[0])])
        .assert()
        .success()
        .stdout(predicate::str::contains(": done"));
    unclop(&p)
        .args(["done", &format!("{}:1,2,3", ids[1]), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(": done"))
        .stdout(predicate::str::contains("gone from source").not());

    let report = json(&p, &["report", "--__JSON__"]);
    let twins_report: Vec<&Value> = report["files"]
        .as_array()
        .unwrap()
        .iter()
        .filter(|f| f["path"] == "src/twins.rs")
        .flat_map(|f| f["items"].as_array().unwrap().iter())
        .filter(|i| i["kind"] == "var")
        .collect();
    assert_eq!(twins_report.len(), 2, "{twins_report:#?}");
    assert_eq!(twins_report[0]["text"], "total");
    assert_eq!(twins_report[0]["was"], "running_total");
    assert_eq!(twins_report[1]["text"], "running_total");
    assert_eq!(twins_report[1]["was"], Value::Null);
    assert!(twins_report.iter().all(|i| i["status"] == "done"));
}

/// A project with only `files` and the test config.
fn bare(files: &[(&str, &str)]) -> Project {
    let dir = tempfile::tempdir().unwrap();
    for (path, src) in files {
        let path = dir.path().join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, src).unwrap();
    }
    let config = dir.path().join("config.yaml");
    fs::write(&config, CONFIG).unwrap();
    Project { dir, config }
}

fn var_ids(p: &Project) -> Vec<String> {
    let chunk = json(p, &["next", "--__JSON__"]);
    items(&chunk)
        .iter()
        .filter(|i| i["kind"] == "var")
        .map(|i| i["id"].as_str().unwrap().to_string())
        .collect()
}

fn stdout_of(c: &mut Command) -> String {
    String::from_utf8(c.output().unwrap().stdout).unwrap()
}

#[test]
fn the_same_name_in_two_files_gets_two_ids() {
    let p = bare(&[
        ("src/a.rs", "pub fn load(config_path: &str) {}\n"),
        ("src/b.rs", "pub fn save(config_path: &str) {}\n"),
    ]);
    unclop(&p).arg("init").assert().success();
    let text = stdout_of(unclop(&p).arg("next"));
    let done_line = text
        .lines()
        .find(|l| l.starts_with("  unclop done "))
        .expect("a done command");
    let args: Vec<&str> = done_line.split_whitespace().skip(2).collect();
    let mut ids: Vec<&str> = args.iter().map(|a| a.split(':').next().unwrap()).collect();
    ids.sort();
    ids.dedup();
    assert_eq!(ids.len(), args.len(), "ids repeat: {done_line}");

    unclop(&p)
        .arg("done")
        .args(&args)
        .arg("--keep")
        .assert()
        .success()
        .stdout(predicate::str::contains("gone").not());
    unclop(&p)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains("Nothing pending"));
}

#[test]
fn an_ambiguous_prefix_is_not_called_gone() {
    let p = bare(&[("src/twins.rs", TWINS)]);
    unclop(&p).arg("init").assert().success();
    let ids = var_ids(&p);
    unclop(&p)
        .args(["done", &format!("{}:1,2,3", &ids[0][..6]), "--keep"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains("matches 2 items"))
        .stdout(predicate::str::contains("gone").not());
}

#[test]
fn the_id_in_a_reply_reaches_the_same_item() {
    let p = bare(&[("src/twins.rs", TWINS)]);
    unclop(&p).arg("init").assert().success();
    let ids = var_ids(&p);
    fs::write(p.dir.path().join("src/twins.rs"), TWINS_EDITED).unwrap();

    // The untouched copy is refused as unchanged; the reply names it.
    let reply = stdout_of(unclop(&p).args(["done", &format!("{}:1,2,3", ids[1])]));
    let named = reply.split(':').next().unwrap().to_string();
    assert!(reply.contains("unchanged since it was issued"), "{reply}");

    // Retrying with the id from the reply marks that same copy.
    unclop(&p)
        .args(["done", &format!("{named}:1,2,3"), "--keep"])
        .assert()
        .success();
    let report = json(&p, &["report", "--__JSON__"]);
    let settled: Vec<&Value> = report["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter())
        .filter(|i| i["kind"] == "var")
        .collect();
    assert_eq!(settled.len(), 1, "{settled:#?}");
    assert_eq!(settled[0]["text"], "running_total");
}

#[test]
fn deleting_one_of_two_copies() {
    let p = bare(&[("src/twins.rs", TWINS)]);
    unclop(&p).arg("init").assert().success();
    let ids = var_ids(&p);
    fs::write(
        p.dir.path().join("src/twins.rs"),
        "fn one() { }\nfn two() { let running_total = 2; }\n",
    )
    .unwrap();

    let out = unclop(&p).arg("next").output().unwrap();
    assert_eq!(out.status.code(), Some(2));
    let listed = String::from_utf8(out.stdout).unwrap();
    let survivors: Vec<&str> = listed
        .lines()
        .filter(|l| l.contains("running_total"))
        .collect();
    assert_eq!(survivors.len(), 1, "{listed}");
    assert!(
        survivors[0].starts_with(&format!("  {} ", ids[1])),
        "{listed}"
    );

    unclop(&p)
        .args(["done", &format!("{}:1,2,3", ids[0])])
        .assert()
        .success()
        .stdout(predicate::str::contains(format!(
            "{}: gone from source",
            ids[0]
        )));
    unclop(&p)
        .args(["done", &format!("{}:1,2,3", ids[1]), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(format!("{}: done", ids[1])));
}

#[test]
fn deleting_one_of_two_identical_comments_in_one_function() {
    let comment = "// Leverage the robust helper seamlessly";
    let p = bare(&[(
        "src/a.rs",
        &format!("fn f() {{\n    {comment}\n    a();\n    {comment}\n    b();\n}}\n"),
    )]);
    unclop(&p).arg("init").assert().success();
    let chunk = json(&p, &["next", "--__JSON__"]);
    let ids: Vec<String> = items(&chunk)
        .iter()
        .filter(|i| i["kind"] == "comment")
        .map(|i| i["id"].as_str().unwrap().to_string())
        .collect();
    assert_eq!(ids.len(), 2);
    fs::write(
        p.dir.path().join("src/a.rs"),
        format!("fn f() {{\n    a();\n    {comment}\n    b();\n}}\n"),
    )
    .unwrap();

    unclop(&p)
        .args(["done", &format!("{}:1,2", ids[0])])
        .assert()
        .success()
        .stdout(predicate::str::contains(format!(
            "{}: gone from source",
            ids[0]
        )));
    unclop(&p)
        .args(["done", &format!("{}:1,2", ids[1]), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(format!("{}: done", ids[1])));
}

#[test]
fn a_path_with_a_hash() {
    let p = bare(&[("src/c#/a.rs", "pub fn handle_request() {}\n")]);
    unclop(&p).arg("init").assert().success();
    let chunk = json(&p, &["next", "--__JSON__"]);
    let id = items(&chunk)[0]["id"].as_str().unwrap().to_string();
    unclop(&p)
        .args(["done", &format!("{id}:1,2,3"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(": done"));
    unclop(&p)
        .args(["reopen", &format!("src/c#/a.rs#{id}")])
        .assert()
        .success()
        .stdout(predicate::str::contains("pending again"));
}

#[test]
fn changing_min_words_applies_to_unchanged_files() {
    let p = bare(&[(
        "src/a.rs",
        "pub fn f() -> &'static str { \"three word message\" }\n",
    )]);
    unclop(&p).arg("init").assert().success();
    let strings = |p: &Project| {
        items(&json(p, &["next", "--force", "--__JSON__"]))
            .iter()
            .filter(|i| i["kind"] == "string")
            .count()
    };
    assert_eq!(strings(&p), 1);
    fs::write(&p.config, CONFIG.replace("min_words: 2", "min_words: 4")).unwrap();
    assert_eq!(strings(&p), 0);
}

#[test]
fn commands_use_the_state_in_a_parent_directory() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    let src = p.dir.path().join("src");
    let in_src = || {
        let mut c = Command::cargo_bin("unclop").unwrap();
        c.current_dir(&src).env("UNCLOP_CONFIG", &p.config);
        c
    };
    in_src()
        .arg("status")
        .assert()
        .code(1)
        .stdout(predicate::str::contains("src/lib.rs"));
    assert!(!src.join(".unclop.jsonl").exists());
    // A path given from the subdirectory is relative to it.
    in_src()
        .args(["skip", "--file", "gen.rs"])
        .assert()
        .success()
        .stdout(predicate::str::contains("src/gen.rs: file skipped"));

    let empty = tempfile::tempdir().unwrap();
    Command::cargo_bin("unclop")
        .unwrap()
        .current_dir(empty.path())
        .env("UNCLOP_CONFIG", &p.config)
        .arg("status")
        .assert()
        .code(70)
        .stderr(predicate::str::contains("unclop init"));
    assert!(!empty.path().join(".unclop.jsonl").exists());
}

#[test]
fn skip_file_resolves_dot_dot() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    unclop(&p)
        .args(["skip", "--file", "src/../src/gen.rs"])
        .assert()
        .success()
        .stdout(predicate::str::contains("src/gen.rs: file skipped"));
    let chunk = json(&p, &["next", "--__JSON__"]);
    assert!(items(&chunk).iter().all(|i| i["path"] != "src/gen.rs"));
}

#[test]
fn skipping_a_file_before_it_exists_sticks() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    unclop(&p)
        .args(["skip", "--file", "src/later.rs"])
        .assert()
        .success();
    unclop(&p).arg("status").assert().code(1);
    fs::write(
        p.dir.path().join("src/later.rs"),
        "pub fn generated_later() {}\n",
    )
    .unwrap();
    let chunk = json(&p, &["next", "--__JSON__"]);
    assert!(items(&chunk).iter().all(|i| i["path"] != "src/later.rs"));
}

#[test]
fn skipping_a_file_unclop_does_not_review_is_refused() {
    let p = setup();
    fs::write(p.dir.path().join("README.md"), "# readme\n").unwrap();
    unclop(&p).arg("init").assert().success();
    unclop(&p)
        .args(["skip", "--file", "README.md"])
        .assert()
        .code(1)
        .stdout(predicate::str::contains(
            "README.md: unclop does not review this file",
        ));
}

#[test]
fn reopen_keeps_the_original_text() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    let chunk = json(&p, &["next", "--__JSON__"]);
    let var_id = id_where(&items(&chunk), |i| i["text"] == "processed_result");
    fs::write(p.dir.path().join("src/lib.rs"), LIB_EDITED).unwrap();
    unclop(&p)
        .args(["done", &format!("{var_id}:1,2,3")])
        .assert()
        .success();

    let renamed = |p: &Project| -> Value {
        json(p, &["report", "--__JSON__"])["files"]
            .as_array()
            .unwrap()
            .iter()
            .flat_map(|f| f["items"].as_array().unwrap().iter().cloned())
            .find(|i| i["kind"] == "var" && i["path"] == "src/lib.rs" && i["text"] != "message")
            .expect("the renamed variable is settled")
    };
    let id = renamed(&p)["id"].as_str().unwrap().to_string();
    unclop(&p).args(["reopen", &id]).assert().success();
    unclop(&p)
        .args(["done", &format!("{id}:1,2,3"), "--keep"])
        .assert()
        .success();
    assert_eq!(renamed(&p)["was"], "processed_result");
}

#[test]
fn missing_config_points_at_init() {
    let p = setup();
    fs::remove_file(&p.config).unwrap();
    unclop(&p)
        .arg("next")
        .assert()
        .code(70)
        .stderr(predicate::str::contains("unclop init"));
}
