//! End-to-end loop through the binary: init, next, edit, done, skip, status, report.

use std::fs;
use std::path::PathBuf;

use assert_cmd::Command;
use predicates::prelude::*;
use serde_json::Value;
use tempfile::TempDir;

const CONFIG: &str = r#"
prompt: |
  PROMPT PLACEHOLDER
rules:
  comment:
    - plain english
    - says why
  identifier:
    - plain english
    - no filler
    - fits convention
  string:
    - plain english
chunk_size: 50
strings:
  min_words: 2
"#;

const LIB: &str = r#"/// Utilizes the robust helper to seamlessly parse the input.
pub fn process_validated_user_data_result(validated_input: &str) -> String {
    // Leverage the helper to compute the final result
    let processed_result = validated_input.trim();
    let message = "An unexpected error has occurred while processing";
    processed_result.to_string() + message
}
"#;

const LIB_EDITED: &str = r#"/// Utilizes the robust helper to seamlessly parse the input.
pub fn process_validated_user_data_result(validated_input: &str) -> String {
    let result = validated_input.trim();
    let message = "An unexpected error has occurred while processing";
    result.to_string() + message
}
"#;

const GEN: &str = r#"// Code generated by tool. DO NOT EDIT.
pub fn generated_helper_function_one(generated_argument: i32) -> i32 { generated_argument }
"#;

const OTHER: &str = r#"pub struct SomeOtherType {
    pub some_field_name: u32,
}
"#;

struct Project {
    dir: TempDir,
    config: PathBuf,
}

fn setup() -> Project {
    let dir = tempfile::tempdir().unwrap();
    fs::create_dir_all(dir.path().join("src")).unwrap();
    fs::write(dir.path().join("src/lib.rs"), LIB).unwrap();
    fs::write(dir.path().join("src/gen.rs"), GEN).unwrap();
    fs::write(dir.path().join("src/other.rs"), OTHER).unwrap();
    let config = dir.path().join("config.yaml");
    fs::write(&config, CONFIG).unwrap();
    Project { dir, config }
}

fn unclop(p: &Project) -> Command {
    let mut c = Command::cargo_bin("unclop").unwrap();
    c.current_dir(p.dir.path()).env("UNCLOP_CONFIG", &p.config);
    c
}

fn json(p: &Project, args: &[&str]) -> Value {
    let out = unclop(p).args(args).output().unwrap();
    serde_json::from_slice(&out.stdout).unwrap_or_else(|e| {
        panic!(
            "not json: {e}\n{}\n{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        )
    })
}

fn items(next: &Value) -> Vec<Value> {
    next["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter().cloned())
        .collect()
}

fn id_where(items: &[Value], f: impl Fn(&Value) -> bool) -> String {
    items
        .iter()
        .find(|i| f(i))
        .unwrap_or_else(|| panic!("no item matched in {items:#?}"))["id"]
        .as_str()
        .unwrap()
        .to_string()
}

#[test]
fn full_loop() {
    let p = setup();

    unclop(&p)
        .arg("init")
        .assert()
        .success()
        .stdout(predicate::str::contains("Scanned 3 files"))
        .stdout(predicate::str::contains("then: unclop next"));

    unclop(&p)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains("PROMPT PLACEHOLDER"))
        .stdout(predicate::str::contains("Rules for identifiers:"))
        .stdout(predicate::str::contains("## src/gen.rs"))
        .stdout(predicate::str::contains("## src/lib.rs"))
        .stdout(predicate::str::contains("unclop done "))
        .stdout(predicate::str::contains(
            "process_validated_user_data_result",
        ));

    // The first chunk holds everything, so re-asking without progress is refused.
    unclop(&p)
        .arg("next")
        .assert()
        .code(2)
        .stdout(predicate::str::contains("Unfinished from your last chunk"));

    let chunk = json(&p, &["next", "--force", "--json"]);
    assert_eq!(chunk["exit_code"], 0);
    let all = items(&chunk);
    let in_lib = |i: &Value| i["path"] == "src/lib.rs";
    let doc_id = id_where(&all, |i| in_lib(i) && i["kind"] == "doc");
    let comment_id = id_where(&all, |i| in_lib(i) && i["kind"] == "comment");
    let var_id = id_where(&all, |i| i["text"] == "processed_result");
    let string_id = id_where(&all, |i| in_lib(i) && i["kind"] == "string");
    let param_id = id_where(&all, |i| i["text"] == "validated_input");
    assert_eq!(
        all.iter().find(|i| i["id"] == var_id.as_str()).unwrap()["rules"],
        "1,2,3"
    );

    // Rename the variable, delete the comment, leave the doc alone.
    fs::write(p.dir.path().join("src/lib.rs"), LIB_EDITED).unwrap();

    unclop(&p)
        .args([
            "done",
            &format!("{var_id}:1,2,3"),
            &format!("{comment_id}:1,2"),
            &format!("{doc_id}:1,2"),
        ])
        .assert()
        .code(1)
        .stdout(predicate::str::contains(": done"))
        .stdout(predicate::str::contains(
            "gone from source, counted as done",
        ))
        .stdout(predicate::str::contains("unchanged since it was issued"));

    unclop(&p)
        .args(["done", &format!("{doc_id}:1,2"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(format!("{doc_id}: done")));

    // Partial ticks leave the item pending and say what is left.
    unclop(&p)
        .args(["done", &format!("{string_id}:1"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains(": done"));
    unclop(&p)
        .args(["done", &format!("{param_id}:1,3"), "--keep"])
        .assert()
        .success()
        .stdout(predicate::str::contains("rules 2 still unchecked"));

    unclop(&p)
        .args(["skip", "--file", "src/gen.rs"])
        .assert()
        .success()
        .stdout(predicate::str::contains("src/gen.rs: file skipped"));

    unclop(&p)
        .arg("status")
        .assert()
        .code(1)
        .stdout(predicate::str::contains("src/gen.rs"))
        .stdout(predicate::str::contains("pending"));

    // Skip whatever is left, then everything is settled.
    let status = json(&p, &["status", "--json"]);
    assert!(status["pending"].as_u64().unwrap() > 0);
    let remaining = json(&p, &["next", "--force", "--json"]);
    let left: Vec<String> = items(&remaining)
        .iter()
        .map(|i| i["id"].as_str().unwrap().to_string())
        .collect();
    assert!(!left.is_empty());
    let mut skip = unclop(&p);
    skip.arg("skip");
    for id in &left {
        skip.arg(id);
    }
    skip.assert().success();

    unclop(&p).arg("status").assert().success();

    unclop(&p)
        .arg("next")
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "Nothing pending. Run: unclop report",
        ));

    unclop(&p)
        .arg("report")
        .assert()
        .success()
        .stdout(predicate::str::contains("was: processed_result"))
        .stdout(predicate::str::contains("kept: Utilizes the robust helper"))
        .stdout(predicate::str::contains("skipped:"))
        .stdout(predicate::str::contains("Skipped files:"))
        .stdout(predicate::str::contains("src/gen.rs"));

    // The renamed variable is resolvable by the id it was issued under.
    let report = json(&p, &["report", "--json"]);
    let renamed = report["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter())
        .find(|i| i["was"] == "processed_result")
        .expect("renamed item in report");
    assert_eq!(renamed["text"], "result");
    assert_eq!(renamed["status"], "done");
}

#[test]
fn workers_split_files() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    let a = json(&p, &["next", "--worker", "1/2", "--json"]);
    let b = json(&p, &["next", "--worker", "2/2", "--json"]);
    let files = |v: &Value| -> Vec<String> {
        v["files"]
            .as_array()
            .unwrap()
            .iter()
            .map(|f| f["path"].as_str().unwrap().to_string())
            .collect()
    };
    let (fa, fb) = (files(&a), files(&b));
    assert!(
        fa.iter().all(|f| !fb.contains(f)),
        "workers overlap: {fa:?} {fb:?}"
    );
    let mut all = fa.clone();
    all.extend(fb);
    all.sort();
    assert_eq!(all, vec!["src/gen.rs", "src/lib.rs", "src/other.rs"]);
}

#[test]
fn reopen_changed_after_done() {
    let p = setup();
    unclop(&p).arg("init").assert().success();
    let chunk = json(&p, &["next", "--json"]);
    let all = items(&chunk);
    let var_id = id_where(&all, |i| i["text"] == "processed_result");
    unclop(&p)
        .args(["done", &format!("{var_id}:1,2,3"), "--keep"])
        .assert()
        .success();

    // A later edit to a done item keeps it done but flags it.
    fs::write(p.dir.path().join("src/lib.rs"), LIB_EDITED).unwrap();
    let report = json(&p, &["report", "--json"]);
    let item = report["files"]
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|f| f["items"].as_array().unwrap().iter())
        .find(|i| i["text"] == "result")
        .expect("renamed item");
    assert_eq!(item["status"], "done");

    unclop(&p)
        .args(["reopen", "--changed"])
        .assert()
        .success()
        .stdout(predicate::str::contains("1 items that changed"));
    let status = json(&p, &["status", "--json"]);
    assert_eq!(status["totals"]["done"], 0);
}

#[test]
fn only_takes_one_category() {
    let p = setup();
    unclop(&p).arg("init").assert().success();

    unclop(&p)
        .args(["next", "--only", "identifier"])
        .assert()
        .success()
        .stdout(predicate::str::contains("Rules for identifiers:"))
        .stdout(predicate::str::contains("Rules for comments:").not())
        .stdout(predicate::str::contains("pending identifiers in this file"));

    let chunk = json(&p, &["next", "--only", "identifiers", "--force", "--json"]);
    assert_eq!(chunk["only"], "identifier");
    let idents = items(&chunk);
    assert!(!idents.is_empty());
    assert!(idents.iter().all(|i| i["category"] == "identifiers"));

    let mut skip = unclop(&p);
    skip.arg("skip");
    for i in &idents {
        skip.arg(i["id"].as_str().unwrap());
    }
    skip.assert().success();

    unclop(&p)
        .args(["next", "--only", "identifier"])
        .assert()
        .success()
        .stdout(predicate::str::contains("No identifiers pending."))
        .stdout(predicate::str::contains("remain in other categories"));

    let chunk = json(&p, &["next", "--only", "comment", "--json"]);
    let comments = items(&chunk);
    assert!(!comments.is_empty());
    assert!(comments.iter().all(|i| i["category"] == "comments"));

    unclop(&p)
        .args(["next", "--only", "names"])
        .assert()
        .code(2)
        .stderr(predicate::str::contains("identifier, comment or string"));
}

#[test]
fn missing_config_points_at_init() {
    let p = setup();
    fs::remove_file(&p.config).unwrap();
    unclop(&p)
        .arg("next")
        .assert()
        .code(70)
        .stderr(predicate::str::contains("unclop init"));
}
